require('mk.plugins.startup')

require('mk.plugins.configs.easyalign')
require('mk.plugins.configs.gitsigns')
require('mk.plugins.configs.gruvbox-flat')
require('mk.plugins.configs.lualine')
require('mk.plugins.configs.nerdtree')
require('mk.plugins.configs.telescope')
require('mk.plugins.configs.treesitter')
require('mk.plugins.configs.vimwiki')
